/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/agent-kinds': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Agent Kinds List
     * @description Every agent a person can add, with whether its program is installed on this machine.
     */
    get: operations['agent_kinds_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/approvals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Approvals List
     * @description Pending approvals first, then the settled ones, each group newest first.
     */
    get: operations['approvals_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/approvals/{approval_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Approvals Get */
    get: operations['approvals_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/approvals/{approval_id}/decision': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Approvals Decide
     * @description Approve or reject. A repeated key answers with the decision it already made.
     */
    post: operations['approvals_decide']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/approvals/{approval_id}/step-up': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Approvals Step Up
     * @description A passkey challenge bound to this approval and this session.
     */
    post: operations['approvals_step_up']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/credentials': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Auth Credentials List */
    get: operations['auth_credentials_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/credentials/{credential_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Auth Credentials Revoke */
    delete: operations['auth_credentials_revoke']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/enroll/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Enroll Options */
    post: operations['auth_enroll_options']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/enroll/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Enroll Verify */
    post: operations['auth_enroll_verify']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/enrollment-links': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Auth Enrollment Links Create
     * @description A one-time link for another passkey, with a QR code to open it on a phone.
     */
    post: operations['auth_enrollment_links_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Login Options */
    post: operations['auth_login_options']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Login Verify */
    post: operations['auth_login_verify']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Logout */
    post: operations['auth_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Auth Status
     * @description Whether this browser is signed in, without a 401 for the login page to special-case.
     */
    get: operations['auth_status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/step-up/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Auth Step Up Options
     * @description Challenge for one purpose, such as `approval:42`; the approval endpoint checks the answer.
     */
    post: operations['auth_step_up_options']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Get
     * @description Answer without a session, so a probe or the UI can tell the server is up.
     */
    get: operations['health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health/rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Rules List
     * @description Every rule with its reason, creator and latest result.
     */
    get: operations['rules_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health/rules/{rule_id}/enabled': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Rules Set Enabled
     * @description Enable or disable a rule, recorded with the signed-in owner as `by`.
     */
    post: operations['rules_set_enabled']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/meetings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Meetings List
     * @description Newest first. The cursor is the last id served, so a new meeting never shifts a page.
     */
    get: operations['meetings_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/meetings/{meeting_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Meetings Get
     * @description The whole meeting from the database alone, so it reads the same with chat disconnected.
     */
    get: operations['meetings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/meetings/{meeting_id}/messages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Meetings Join
     * @description Say something as the owner; the next turns of the meeting see it.
     */
    post: operations['meetings_join']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/org/ceo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ceo Get
     * @description The global CEO assignment, or empty fields before it has been configured.
     */
    get: operations['ceo_get']
    /**
     * Ceo Put
     * @description Configure one CEO for all projects without replacing its identity or team.
     */
    put: operations['ceo_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/org/ceo/messages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Ceo Messages Get
     * @description Recent direct messages, including queued and failed turns.
     */
    get: operations['ceo_messages_get']
    put?: never
    /**
     * Ceo Messages Post
     * @description Queue one owner turn through the CEO's normal scheduler, budget and backup path.
     */
    post: operations['ceo_messages_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Projects List
     * @description One card per project: budget, open tasks by status and the latest deliverable.
     */
    get: operations['projects_list']
    put?: never
    /**
     * Projects Create
     * @description Register an existing directory on this machine as a project.
     */
    post: operations['projects_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/of-task/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Projects Of Task
     * @description The project that owns a task, so a link to a task can open its project.
     */
    get: operations['projects_of_task']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/{project_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Projects Get
     * @description The project's team tree, deliverables, tasks by status and budget.
     */
    get: operations['projects_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/{project_id}/adopt-manager': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Adopt Manager Request
     * @description Ask approval before moving an owner's running tmux agent into labhq.
     */
    post: operations['adopt_manager_request']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/{project_id}/agents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Project Agents Create
     * @description Add an agent to a project. It starts pending: nothing runs until its approval.
     */
    post: operations['project_agents_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/{project_id}/agents/{agent_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Project Agent Update
     * @description Edit an existing assignment without creating another agent or manager.
     */
    patch: operations['project_agent_update']
    trace?: never
  }
  '/api/projects/{project_id}/assign-saved-session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Assign Saved Session */
    post: operations['assign_saved_session']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/{project_id}/running-managers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Running Managers List
     * @description Show CLI agents in the owner's tmux that can be adopted for this project.
     */
    get: operations['running_managers_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/projects/{project_id}/saved-sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Saved Sessions List
     * @description List exact sessions of the selected CLI in this project's directory.
     */
    get: operations['saved_sessions_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/repository-browser': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Repository Browser Get
     * @description List visible directories only; the create route validates the chosen folder.
     */
    get: operations['repository_browser_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/repository-browser/suggest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Repository Browser Suggest
     * @description Find a few visible server folders by name or partial path for project entry.
     */
    get: operations['repository_browser_suggest']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Today Get
     * @description What was delivered since `since`, and what needs the owner now.
     */
    get: operations['today_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/vocabulary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Vocabulary Get
     * @description The backend's status values; the UI maps each one onto its own states.
     */
    get: operations['vocabulary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ActionItem */
    ActionItem: {
      /** Assignee Agent Id */
      assignee_agent_id: number | null
      /** Assignee Name */
      assignee_name: string | null
      /** Decision Id */
      decision_id: number | null
      /** Id */
      id: number
      /** Task Id */
      task_id: number
      task_status: components['schemas']['TaskStatus']
      /** Task Title */
      task_title: string
      /** Text */
      text: string
    }
    /** AddedAgent */
    AddedAgent: {
      /** Adapter */
      adapter: string
      /** Approval Id */
      approval_id: number
      /** Budget Micros */
      budget_micros: number | null
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Project Id */
      project_id: number
      /** Reports To */
      reports_to: number | null
      /** Role */
      role: string
      status: components['schemas']['AgentStatus']
      /** Title */
      title: string
    }
    /** AdoptManagerApproval */
    AdoptManagerApproval: {
      /** Approval Id */
      approval_id: number
      /** Warnings */
      warnings: string[]
    }
    /** AdoptManagerBody */
    AdoptManagerBody: {
      /** Pid */
      pid: number
    }
    /** AgentKindChoice */
    AgentKindChoice: {
      /** Adapter */
      adapter: string
      /** Available */
      available: boolean
      /** Binary */
      binary: string
      /** Display Name */
      display_name: string
      /** Name */
      name: string
    }
    /** AgentRef */
    AgentRef: {
      /** Id */
      id: number
      /** Role */
      role: string
      /** Title */
      title: string
    }
    /**
     * AgentStatus
     * @enum {string}
     */
    AgentStatus: 'pending_approval' | 'active' | 'paused' | 'retired'
    /** ApprovalOut */
    ApprovalOut: {
      /** Branch */
      branch: string | null
      /** Confirmation Kind */
      confirmation_kind: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Decided At */
      decided_at: string | null
      /** Decided By */
      decided_by: string | null
      /** Decision Note */
      decision_note: string | null
      /** Executed At */
      executed_at: string | null
      /** Execution */
      execution: {
        [key: string]: unknown
      } | null
      /** Id */
      id: number
      /** Payload */
      payload: {
        [key: string]: unknown
      }
      project: components['schemas']['labhq__api__approvals__schemas__ProjectRef'] | null
      /** Remote */
      remote: string | null
      requester: components['schemas']['AgentRef'] | null
      risk_class: components['schemas']['RiskClass']
      status: components['schemas']['ApprovalStatus']
      task: components['schemas']['TaskRef'] | null
      /** Type */
      type: string
    }
    /**
     * ApprovalStatus
     * @enum {string}
     */
    ApprovalStatus:
      'pending' | 'approved' | 'rejected' | 'executed' | 'execution_failed' | 'cancelled'
    /** AssertionBody */
    AssertionBody: {
      /** Credential */
      credential: {
        [key: string]: unknown
      }
    }
    /** AssignSavedSessionBody */
    AssignSavedSessionBody: {
      /** Kind */
      kind: string
      /** Session Id */
      session_id: string
    }
    /** AuthStatus */
    AuthStatus: {
      /** Authenticated */
      authenticated: boolean
      /** Enrolled */
      enrolled: boolean
    }
    /** BrowserFolder */
    BrowserFolder: {
      /** Name */
      name: string
      /** Path */
      path: string
    }
    /** BrowserListing */
    BrowserListing: {
      /** Folders */
      folders: components['schemas']['BrowserFolder'][]
      /** Parent */
      parent: string | null
      /** Path */
      path: string | null
      /** Roots */
      roots: components['schemas']['BrowserFolder'][]
    }
    /**
     * Budget
     * @description One budget level as `labhq.budgets` reads it, for the current period.
     */
    Budget: {
      /**
       * Budget Micros
       * @description The limit; absent means no limit.
       */
      budget_micros: number | null
      /** Spent Micros */
      spent_micros: number
      state: components['schemas']['labhq__budgets__decision__Decision']
      /** Used Percent */
      used_percent: number | null
    }
    /**
     * BudgetNotice
     * @description A budget that crossed its warning line in the current period.
     */
    BudgetNotice: {
      /** Budget Micros */
      budget_micros: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Name */
      name: string
      scope: components['schemas']['BudgetScope']
      /** Scope Id */
      scope_id: number
      /** Spent Micros */
      spent_micros: number
    }
    /** BudgetPolicy */
    BudgetPolicy: {
      /**
       * Period Start
       * Format: date-time
       */
      period_start: string
      /** Stop Percent */
      stop_percent: number
      /** Warn Percent */
      warn_percent: number
    }
    /**
     * BudgetScope
     * @enum {string}
     */
    BudgetScope: 'agent' | 'project'
    /**
     * CallRequestStatus
     * @enum {string}
     */
    CallRequestStatus: 'pending' | 'answered' | 'failed' | 'expired'
    /**
     * CallStatus
     * @enum {string}
     */
    CallStatus: 'open' | 'closed'
    /** CeoAssignment */
    CeoAssignment: {
      /** Backup Kind */
      backup_kind: string | null
      /** Id */
      id: number | null
      /** Primary Kind */
      primary_kind: string | null
    }
    /** CeoChatTurn */
    CeoChatTurn: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Reply */
      reply: string | null
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'answered' | 'failed'
      /** Text */
      text: string
    }
    /**
     * Credential
     * @description What the UI may know about a passkey. The public key stays on the server.
     */
    Credential: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Last Used At */
      last_used_at: string | null
      /** Name */
      name: string
      /** Revoked */
      revoked: boolean
      /** Rp Id */
      rp_id: string
      /** Transports */
      transports: string[]
    }
    /** DecisionBody */
    DecisionBody: {
      /** Credential */
      credential?: {
        [key: string]: unknown
      } | null
      /**
       * Decision
       * @enum {string}
       */
      decision: 'approve' | 'reject'
      /** Note */
      note?: string | null
    }
    /**
     * Deliverable
     * @description A done task and what it produced.
     */
    Deliverable: {
      /** Branch */
      branch: string
      /** Commits */
      commits: string[]
      /** Cost Micros */
      cost_micros: number
      /**
       * Done At
       * Format: date-time
       */
      done_at: string
      /** Task Id */
      task_id: number
      /** Title */
      title: string
    }
    /** EnrollOptionsBody */
    EnrollOptionsBody: {
      /** Token */
      token: string
    }
    /** EnrollVerifyBody */
    EnrollVerifyBody: {
      /** Credential */
      credential: {
        [key: string]: unknown
      }
      /**
       * Name
       * @default Passkey
       */
      name: string
      /** Token */
      token: string
    }
    /** EnrollmentLink */
    EnrollmentLink: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /** Qr */
      qr: string
      /** Url */
      url: string
    }
    /** EnrollmentLinkBody */
    EnrollmentLinkBody: {
      /**
       * Target
       * @default public
       * @enum {string}
       */
      target: 'public' | 'here'
    }
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string
      /** Message */
      message: string
    }
    /** ErrorEnvelope */
    ErrorEnvelope: {
      error: components['schemas']['ErrorBody']
    }
    /** ExecutedApproval */
    ExecutedApproval: {
      /** Branch */
      branch: string | null
      /** Commit */
      commit: string | null
      /** Id */
      id: number
      status: components['schemas']['ApprovalStatus']
      /** Type */
      type: string
    }
    /** Health */
    Health: {
      /** Version */
      version: string
    }
    /**
     * HealthRuleAction
     * @enum {string}
     */
    HealthRuleAction: 'notify' | 'ticket'
    /** HealthRuleEnabledBody */
    HealthRuleEnabledBody: {
      /** Enabled */
      enabled: boolean
    }
    /** HealthRuleItem */
    HealthRuleItem: {
      action: components['schemas']['HealthRuleAction']
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Created By */
      created_by: string
      /** Enabled */
      enabled: boolean
      /** Host */
      host: string | null
      /** Id */
      id: number
      latest: components['schemas']['HealthRuleLatest'] | null
      /** Name */
      name: string
      /** Params */
      params: {
        [key: string]: unknown
      }
      /** Reason */
      reason: string
      /** Type */
      type: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * HealthRuleLatest
     * @description The rule's most recent incident, open or resolved: what it last observed.
     */
    HealthRuleLatest: {
      /** Details */
      details: {
        [key: string]: unknown
      }
      /** Incident Id */
      incident_id: number
      /**
       * Opened At
       * Format: date-time
       */
      opened_at: string
      /** Resolved At */
      resolved_at: string | null
      status: components['schemas']['IncidentStatus']
    }
    /**
     * HostStatus
     * @enum {string}
     */
    HostStatus: 'unknown' | 'up' | 'degraded' | 'down'
    /**
     * IncidentStatus
     * @enum {string}
     */
    IncidentStatus: 'open' | 'resolved'
    /** JoinBody */
    JoinBody: {
      /** Text */
      text: string
    }
    /** MeetingDetail */
    MeetingDetail: {
      /** Action Items */
      action_items: components['schemas']['ActionItem'][]
      /** Agenda */
      agenda: string
      /** Channel */
      channel: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Decisions */
      decisions: components['schemas']['labhq__api__meetings__schemas__Decision'][]
      /** End Reason */
      end_reason: string | null
      /** Ended At */
      ended_at: string | null
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Messages */
      messages: components['schemas']['Message'][]
      /** Participants */
      participants: components['schemas']['Participant'][]
      /** Project Id */
      project_id: number
      /** Project Name */
      project_name: string
      /** Started At */
      started_at: string | null
      status: components['schemas']['MeetingStatus']
    }
    /** MeetingItem */
    MeetingItem: {
      /** Channel */
      channel: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Project Id */
      project_id: number
      /** Project Name */
      project_name: string
      /** Started At */
      started_at: string | null
      status: components['schemas']['MeetingStatus']
    }
    /**
     * MeetingStatus
     * @enum {string}
     */
    MeetingStatus: 'requested' | 'running' | 'ended' | 'failed' | 'cancelled'
    /** Message */
    Message: {
      /** Agent Id */
      agent_id: number | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      source: components['schemas']['TranscriptSource']
      /** Speaker */
      speaker: string
      /** Text */
      text: string
    }
    /** NeedsYou */
    NeedsYou: {
      /** Approvals */
      approvals: components['schemas']['PendingApproval'][]
      /** Budget Warnings */
      budget_warnings: components['schemas']['BudgetNotice'][]
      /** Count */
      count: number
      /** Incidents */
      incidents: components['schemas']['OpenIncident'][]
      /** Questions */
      questions: components['schemas']['PendingQuestion'][]
    }
    /** NewAgentBody */
    NewAgentBody: {
      /** Budget Micros */
      budget_micros?: number | null
      /** Kind */
      kind: string
      /** Reports To */
      reports_to?: number | null
      /** Role */
      role: string
      /** Title */
      title: string
    }
    /** NewProjectBody */
    NewProjectBody: {
      /** Budget Micros */
      budget_micros?: number | null
      /** Name */
      name: string
      /** Repo Path */
      repo_path: string
    }
    /**
     * NotificationStatus
     * @enum {string}
     */
    NotificationStatus: 'pending' | 'sent' | 'failed'
    /** OpenIncident */
    OpenIncident: {
      /** Host Name */
      host_name: string
      /** Id */
      id: number
      /**
       * Opened At
       * Format: date-time
       */
      opened_at: string
      /** Rule Name */
      rule_name: string
      status: components['schemas']['IncidentStatus']
    }
    /** Page[ApprovalOut] */
    Page_ApprovalOut_: {
      /** Items */
      items: components['schemas']['ApprovalOut'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Page[MeetingItem] */
    Page_MeetingItem_: {
      /** Items */
      items: components['schemas']['MeetingItem'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Page[ProjectCard] */
    Page_ProjectCard_: {
      /** Items */
      items: components['schemas']['ProjectCard'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** Participant */
    Participant: {
      /** Agent Id */
      agent_id: number | null
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /** PendingApproval */
    PendingApproval: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Project Id */
      project_id: number | null
      /** Project Name */
      project_name: string | null
      risk_class: components['schemas']['RiskClass']
      status: components['schemas']['ApprovalStatus']
      /** Task Id */
      task_id: number | null
      /** Task Title */
      task_title: string | null
      /** Type */
      type: string
    }
    /** PendingQuestion */
    PendingQuestion: {
      /** Agent Title */
      agent_title: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Project Id */
      project_id: number | null
      /** Question */
      question: string
      status: components['schemas']['QuestionStatus']
      /** Task Id */
      task_id: number | null
    }
    /** ProjectCard */
    ProjectCard: {
      budget: components['schemas']['Budget']
      /** Id */
      id: number
      latest_deliverable: components['schemas']['Deliverable'] | null
      /** Name */
      name: string
      /** Open Tasks */
      open_tasks: components['schemas']['TaskCount'][]
      status: components['schemas']['ProjectStatus']
    }
    /**
     * ProjectStatus
     * @enum {string}
     */
    ProjectStatus: 'active' | 'paused' | 'archived'
    /** ProjectView */
    ProjectView: {
      budget: components['schemas']['Budget']
      /** Deliverables */
      deliverables: components['schemas']['Deliverable'][]
      /** Deliverables Total */
      deliverables_total: number
      /** Id */
      id: number
      /** Name */
      name: string
      policy: components['schemas']['BudgetPolicy']
      status: components['schemas']['ProjectStatus']
      /** Tasks */
      tasks: components['schemas']['TaskCount'][]
      /** Team */
      team: components['schemas']['TeamMember'][]
    }
    /**
     * QuestionStatus
     * @enum {string}
     */
    QuestionStatus: 'pending' | 'answered'
    /** RegisteredProject */
    RegisteredProject: {
      /** Budget Micros */
      budget_micros: number | null
      /** Id */
      id: number
      /** Name */
      name: string
      /** Repo Path */
      repo_path: string
    }
    /**
     * RiskClass
     * @enum {string}
     */
    RiskClass: 'light' | 'heavy'
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus: 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted' | 'timed_out'
    /** RunningManagerCandidate */
    RunningManagerCandidate: {
      /** Cwd */
      cwd: string
      /** Kind */
      kind: string
      /** Pane */
      pane: string
      /** Pid */
      pid: number
    }
    /** SavedSessionChoice */
    SavedSessionChoice: {
      /** Kind */
      kind: string
      /** Session Id */
      session_id: string
      /** Updated At */
      updated_at: string
    }
    /** SendCeoMessage */
    SendCeoMessage: {
      /** Text */
      text: string
    }
    /** SetCeoAssignment */
    SetCeoAssignment: {
      /** Backup Kind */
      backup_kind?: string | null
      /** Primary Kind */
      primary_kind: string
    }
    /** SpendWithoutOutput */
    SpendWithoutOutput: {
      /** Agent Id */
      agent_id: number
      /** Agent Title */
      agent_title: string
      /** Cost Micros */
      cost_micros: number
      /** Project Id */
      project_id: number | null
      /** Project Name */
      project_name: string | null
    }
    /** StepUpBody */
    StepUpBody: {
      /** Purpose */
      purpose: string
    }
    /** TaskCount */
    TaskCount: {
      /** Count */
      count: number
      status: components['schemas']['TaskStatus']
    }
    /** TaskRef */
    TaskRef: {
      /** Id */
      id: number
      /** Title */
      title: string
    }
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'blocked' | 'done' | 'cancelled'
    /** TeamMember */
    TeamMember: {
      /** Adapter */
      adapter: string
      /** Adopted */
      adopted: boolean
      budget: components['schemas']['Budget']
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Reports */
      reports: components['schemas']['TeamMember'][]
      /** Reports To */
      reports_to: number | null
      /** Role */
      role: string
      status: components['schemas']['AgentStatus']
      /** Title */
      title: string
    }
    /** Today */
    Today: {
      /** Deliverables */
      deliverables: components['schemas']['TodayDeliverable'][]
      needs_you: components['schemas']['NeedsYou']
      /**
       * Since
       * Format: date-time
       */
      since: string
      /** Spend Without Output */
      spend_without_output: components['schemas']['SpendWithoutOutput'][]
      /**
       * Until
       * Format: date-time
       */
      until: string
    }
    /** TodayDeliverable */
    TodayDeliverable: {
      /** Approvals */
      approvals: components['schemas']['ExecutedApproval'][]
      /** Branch */
      branch: string | null
      /** Commit Count */
      commit_count: number
      /** Cost Micros */
      cost_micros: number
      /**
       * Finished At
       * Format: date-time
       */
      finished_at: string
      /** Project Id */
      project_id: number
      /** Project Name */
      project_name: string
      /** Task Id */
      task_id: number
      /** Title */
      title: string
    }
    /**
     * TranscriptSource
     * @enum {string}
     */
    TranscriptSource: 'agent' | 'owner' | 'system'
    /** UpdateAgentBody */
    UpdateAgentBody: {
      /** Budget Micros */
      budget_micros?: number | null
      /** Kind */
      kind: string
      /** Reports To */
      reports_to?: number | null
      /** Title */
      title: string
    }
    /** UpdatedAgent */
    UpdatedAgent: {
      /** Budget Micros */
      budget_micros: number | null
      /** Id */
      id: number
      /** Kind */
      kind: string
      /** Reports To */
      reports_to: number | null
      /** Title */
      title: string
    }
    /**
     * Vocabulary
     * @description The status values the backend may return, by enum.
     */
    Vocabulary: {
      /**
       * Agent Status
       * @description Every value of `AgentStatus`.
       */
      agent_status: components['schemas']['AgentStatus'][]
      /**
       * Approval Status
       * @description Every value of `ApprovalStatus`.
       */
      approval_status: components['schemas']['ApprovalStatus'][]
      /**
       * Call Request Status
       * @description Every value of `CallRequestStatus`.
       */
      call_request_status: components['schemas']['CallRequestStatus'][]
      /**
       * Call Status
       * @description Every value of `CallStatus`.
       */
      call_status: components['schemas']['CallStatus'][]
      /**
       * Host Status
       * @description Every value of `HostStatus`.
       */
      host_status: components['schemas']['HostStatus'][]
      /**
       * Incident Status
       * @description Every value of `IncidentStatus`.
       */
      incident_status: components['schemas']['IncidentStatus'][]
      /**
       * Meeting Status
       * @description Every value of `MeetingStatus`.
       */
      meeting_status: components['schemas']['MeetingStatus'][]
      /**
       * Notification Status
       * @description Every value of `NotificationStatus`.
       */
      notification_status: components['schemas']['NotificationStatus'][]
      /**
       * Project Status
       * @description Every value of `ProjectStatus`.
       */
      project_status: components['schemas']['ProjectStatus'][]
      /**
       * Question Status
       * @description Every value of `QuestionStatus`.
       */
      question_status: components['schemas']['QuestionStatus'][]
      /**
       * Run Status
       * @description Every value of `RunStatus`.
       */
      run_status: components['schemas']['RunStatus'][]
      /**
       * Task Status
       * @description Every value of `TaskStatus`.
       */
      task_status: components['schemas']['TaskStatus'][]
      /**
       * Wakeup Status
       * @description Every value of `WakeupStatus`.
       */
      wakeup_status: components['schemas']['WakeupStatus'][]
    }
    /**
     * WakeupStatus
     * @enum {string}
     */
    WakeupStatus: 'pending' | 'dispatched' | 'refused' | 'cancelled'
    /** ProjectRef */
    labhq__api__approvals__schemas__ProjectRef: {
      /** Id */
      id: number
      /** Name */
      name: string
    }
    /** Decision */
    labhq__api__meetings__schemas__Decision: {
      /** Id */
      id: number
      /** Position */
      position: number
      /** Text */
      text: string
    }
    /** ProjectRef */
    labhq__api__projects__schemas__ProjectRef: {
      /** Project Id */
      project_id: number
    }
    /**
     * Decision
     * @enum {string}
     */
    labhq__budgets__decision__Decision: 'allow' | 'warn' | 'stop'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  agent_kinds_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AgentKindChoice'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  approvals_list: {
    parameters: {
      query?: {
        /** @description Only this status. */
        status?: components['schemas']['ApprovalStatus'] | null
        /** @description Opaque; from `next_cursor`. */
        cursor?: string | null
        /** @description Rows per page. */
        limit?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ApprovalOut_']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  approvals_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        approval_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalOut']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  approvals_decide: {
    parameters: {
      query?: never
      header: {
        /** @description One per user intent; a retry reuses it. */
        'idempotency-key': string
      }
      path: {
        approval_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DecisionBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalOut']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  approvals_step_up: {
    parameters: {
      query?: never
      header?: never
      path: {
        approval_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_credentials_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Credential'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_credentials_revoke: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Credential']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_enroll_options: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnrollOptionsBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_enroll_verify: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnrollVerifyBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Credential']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_enrollment_links_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnrollmentLinkBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EnrollmentLink']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_login_options: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_login_verify: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AssertionBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatus']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatus']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_status: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatus']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_step_up_options: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StepUpBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  rules_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthRuleItem'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  rules_set_enabled: {
    parameters: {
      query?: never
      header?: never
      path: {
        rule_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['HealthRuleEnabledBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthRuleItem']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  meetings_list: {
    parameters: {
      query?: {
        /** @description Opaque; from `next_cursor`. */
        cursor?: string | null
        /** @description Rows per page. */
        limit?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_MeetingItem_']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  meetings_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeetingDetail']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  meetings_join: {
    parameters: {
      query?: never
      header?: never
      path: {
        meeting_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinBody']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Message']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  ceo_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CeoAssignment']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  ceo_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetCeoAssignment']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CeoAssignment']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  ceo_messages_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CeoChatTurn'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  ceo_messages_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SendCeoMessage']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CeoChatTurn']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  projects_list: {
    parameters: {
      query?: {
        /** @description Opaque; from `next_cursor`. */
        cursor?: string | null
        /** @description Rows per page. */
        limit?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ProjectCard_']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  projects_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewProjectBody']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegisteredProject']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  projects_of_task: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['labhq__api__projects__schemas__ProjectRef']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  projects_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectView']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  adopt_manager_request: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdoptManagerBody']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdoptManagerApproval']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  project_agents_create: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewAgentBody']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AddedAgent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  project_agent_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: number
        agent_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAgentBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UpdatedAgent']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  assign_saved_session: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AssignSavedSessionBody']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdoptManagerApproval']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  running_managers_list: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunningManagerCandidate'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  saved_sessions_list: {
    parameters: {
      query: {
        kind: string
      }
      header?: never
      path: {
        project_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SavedSessionChoice'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  repository_browser_get: {
    parameters: {
      query?: {
        path?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BrowserListing']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  repository_browser_suggest: {
    parameters: {
      query: {
        query: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BrowserFolder'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  today_get: {
    parameters: {
      query?: {
        /** @description Start of the window; default: the last 24 hours. */
        since?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Today']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  vocabulary_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Vocabulary']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
}
