/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Get
     * @description Answer without a session, so a probe or the UI can tell the server is up.
     */
    get: operations['health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/vocabulary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Vocabulary Get
     * @description The backend's status values; the UI maps each one onto its own states.
     */
    get: operations['vocabulary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AgentStatus
     * @enum {string}
     */
    AgentStatus: 'pending_approval' | 'active' | 'paused' | 'retired'
    /**
     * ApprovalStatus
     * @enum {string}
     */
    ApprovalStatus:
      'pending' | 'approved' | 'rejected' | 'executed' | 'execution_failed' | 'cancelled'
    /**
     * CallRequestStatus
     * @enum {string}
     */
    CallRequestStatus: 'pending' | 'answered' | 'failed' | 'expired'
    /**
     * CallStatus
     * @enum {string}
     */
    CallStatus: 'open' | 'closed'
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string
      /** Message */
      message: string
    }
    /** ErrorEnvelope */
    ErrorEnvelope: {
      error: components['schemas']['ErrorBody']
    }
    /** Health */
    Health: {
      /** Version */
      version: string
    }
    /**
     * HostStatus
     * @enum {string}
     */
    HostStatus: 'unknown' | 'up' | 'degraded' | 'down'
    /**
     * IncidentStatus
     * @enum {string}
     */
    IncidentStatus: 'open' | 'resolved'
    /**
     * NotificationStatus
     * @enum {string}
     */
    NotificationStatus: 'pending' | 'sent' | 'failed'
    /**
     * ProjectStatus
     * @enum {string}
     */
    ProjectStatus: 'active' | 'paused' | 'archived'
    /**
     * QuestionStatus
     * @enum {string}
     */
    QuestionStatus: 'pending' | 'answered'
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus: 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted' | 'timed_out'
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'blocked' | 'done' | 'cancelled'
    /**
     * Vocabulary
     * @description The status values the backend may return, by enum.
     */
    Vocabulary: {
      /**
       * Agent Status
       * @description Every value of `AgentStatus`.
       */
      agent_status: components['schemas']['AgentStatus'][]
      /**
       * Approval Status
       * @description Every value of `ApprovalStatus`.
       */
      approval_status: components['schemas']['ApprovalStatus'][]
      /**
       * Call Request Status
       * @description Every value of `CallRequestStatus`.
       */
      call_request_status: components['schemas']['CallRequestStatus'][]
      /**
       * Call Status
       * @description Every value of `CallStatus`.
       */
      call_status: components['schemas']['CallStatus'][]
      /**
       * Host Status
       * @description Every value of `HostStatus`.
       */
      host_status: components['schemas']['HostStatus'][]
      /**
       * Incident Status
       * @description Every value of `IncidentStatus`.
       */
      incident_status: components['schemas']['IncidentStatus'][]
      /**
       * Notification Status
       * @description Every value of `NotificationStatus`.
       */
      notification_status: components['schemas']['NotificationStatus'][]
      /**
       * Project Status
       * @description Every value of `ProjectStatus`.
       */
      project_status: components['schemas']['ProjectStatus'][]
      /**
       * Question Status
       * @description Every value of `QuestionStatus`.
       */
      question_status: components['schemas']['QuestionStatus'][]
      /**
       * Run Status
       * @description Every value of `RunStatus`.
       */
      run_status: components['schemas']['RunStatus'][]
      /**
       * Task Status
       * @description Every value of `TaskStatus`.
       */
      task_status: components['schemas']['TaskStatus'][]
      /**
       * Wakeup Status
       * @description Every value of `WakeupStatus`.
       */
      wakeup_status: components['schemas']['WakeupStatus'][]
    }
    /**
     * WakeupStatus
     * @enum {string}
     */
    WakeupStatus: 'pending' | 'dispatched' | 'refused' | 'cancelled'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  vocabulary_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Vocabulary']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
}
