/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/credentials': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Auth Credentials List */
    get: operations['auth_credentials_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/credentials/{credential_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Auth Credentials Revoke */
    delete: operations['auth_credentials_revoke']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/enroll/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Enroll Options */
    post: operations['auth_enroll_options']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/enroll/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Enroll Verify */
    post: operations['auth_enroll_verify']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/enrollment-links': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Auth Enrollment Links Create
     * @description A one-time link for another passkey, with a QR code to open it on a phone.
     */
    post: operations['auth_enrollment_links_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Login Options */
    post: operations['auth_login_options']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Login Verify */
    post: operations['auth_login_verify']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Auth Logout */
    post: operations['auth_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Auth Status
     * @description Whether this browser is signed in, without a 401 for the login page to special-case.
     */
    get: operations['auth_status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/step-up/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Auth Step Up Options
     * @description Challenge for one purpose, such as `approval:42`; the approval endpoint checks the answer.
     */
    post: operations['auth_step_up_options']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Get
     * @description Answer without a session, so a probe or the UI can tell the server is up.
     */
    get: operations['health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/vocabulary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Vocabulary Get
     * @description The backend's status values; the UI maps each one onto its own states.
     */
    get: operations['vocabulary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AgentStatus
     * @enum {string}
     */
    AgentStatus: 'pending_approval' | 'active' | 'paused' | 'retired'
    /**
     * ApprovalStatus
     * @enum {string}
     */
    ApprovalStatus:
      'pending' | 'approved' | 'rejected' | 'executed' | 'execution_failed' | 'cancelled'
    /** AssertionBody */
    AssertionBody: {
      /** Credential */
      credential: {
        [key: string]: unknown
      }
    }
    /** AuthStatus */
    AuthStatus: {
      /** Authenticated */
      authenticated: boolean
      /** Enrolled */
      enrolled: boolean
    }
    /**
     * CallRequestStatus
     * @enum {string}
     */
    CallRequestStatus: 'pending' | 'answered' | 'failed' | 'expired'
    /**
     * CallStatus
     * @enum {string}
     */
    CallStatus: 'open' | 'closed'
    /**
     * Credential
     * @description What the UI may know about a passkey. The public key stays on the server.
     */
    Credential: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Id */
      id: number
      /** Last Used At */
      last_used_at: string | null
      /** Name */
      name: string
      /** Revoked */
      revoked: boolean
      /** Rp Id */
      rp_id: string
      /** Transports */
      transports: string[]
    }
    /** EnrollOptionsBody */
    EnrollOptionsBody: {
      /** Token */
      token: string
    }
    /** EnrollVerifyBody */
    EnrollVerifyBody: {
      /** Credential */
      credential: {
        [key: string]: unknown
      }
      /**
       * Name
       * @default Passkey
       */
      name: string
      /** Token */
      token: string
    }
    /** EnrollmentLink */
    EnrollmentLink: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      /** Qr */
      qr: string
      /** Url */
      url: string
    }
    /** EnrollmentLinkBody */
    EnrollmentLinkBody: {
      /**
       * Target
       * @default public
       * @enum {string}
       */
      target: 'public' | 'here'
    }
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string
      /** Message */
      message: string
    }
    /** ErrorEnvelope */
    ErrorEnvelope: {
      error: components['schemas']['ErrorBody']
    }
    /** Health */
    Health: {
      /** Version */
      version: string
    }
    /**
     * HostStatus
     * @enum {string}
     */
    HostStatus: 'unknown' | 'up' | 'degraded' | 'down'
    /**
     * IncidentStatus
     * @enum {string}
     */
    IncidentStatus: 'open' | 'resolved'
    /**
     * MeetingStatus
     * @enum {string}
     */
    MeetingStatus: 'requested' | 'running' | 'ended' | 'failed' | 'cancelled'
    /**
     * NotificationStatus
     * @enum {string}
     */
    NotificationStatus: 'pending' | 'sent' | 'failed'
    /**
     * ProjectStatus
     * @enum {string}
     */
    ProjectStatus: 'active' | 'paused' | 'archived'
    /**
     * QuestionStatus
     * @enum {string}
     */
    QuestionStatus: 'pending' | 'answered'
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus: 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted' | 'timed_out'
    /** StepUpBody */
    StepUpBody: {
      /** Purpose */
      purpose: string
    }
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'blocked' | 'done' | 'cancelled'
    /**
     * Vocabulary
     * @description The status values the backend may return, by enum.
     */
    Vocabulary: {
      /**
       * Agent Status
       * @description Every value of `AgentStatus`.
       */
      agent_status: components['schemas']['AgentStatus'][]
      /**
       * Approval Status
       * @description Every value of `ApprovalStatus`.
       */
      approval_status: components['schemas']['ApprovalStatus'][]
      /**
       * Call Request Status
       * @description Every value of `CallRequestStatus`.
       */
      call_request_status: components['schemas']['CallRequestStatus'][]
      /**
       * Call Status
       * @description Every value of `CallStatus`.
       */
      call_status: components['schemas']['CallStatus'][]
      /**
       * Host Status
       * @description Every value of `HostStatus`.
       */
      host_status: components['schemas']['HostStatus'][]
      /**
       * Incident Status
       * @description Every value of `IncidentStatus`.
       */
      incident_status: components['schemas']['IncidentStatus'][]
      /**
       * Meeting Status
       * @description Every value of `MeetingStatus`.
       */
      meeting_status: components['schemas']['MeetingStatus'][]
      /**
       * Notification Status
       * @description Every value of `NotificationStatus`.
       */
      notification_status: components['schemas']['NotificationStatus'][]
      /**
       * Project Status
       * @description Every value of `ProjectStatus`.
       */
      project_status: components['schemas']['ProjectStatus'][]
      /**
       * Question Status
       * @description Every value of `QuestionStatus`.
       */
      question_status: components['schemas']['QuestionStatus'][]
      /**
       * Run Status
       * @description Every value of `RunStatus`.
       */
      run_status: components['schemas']['RunStatus'][]
      /**
       * Task Status
       * @description Every value of `TaskStatus`.
       */
      task_status: components['schemas']['TaskStatus'][]
      /**
       * Wakeup Status
       * @description Every value of `WakeupStatus`.
       */
      wakeup_status: components['schemas']['WakeupStatus'][]
    }
    /**
     * WakeupStatus
     * @enum {string}
     */
    WakeupStatus: 'pending' | 'dispatched' | 'refused' | 'cancelled'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  auth_credentials_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Credential'][]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_credentials_revoke: {
    parameters: {
      query?: never
      header?: never
      path: {
        credential_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Credential']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_enroll_options: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnrollOptionsBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_enroll_verify: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnrollVerifyBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Credential']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_enrollment_links_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnrollmentLinkBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EnrollmentLink']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_login_options: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_login_verify: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AssertionBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatus']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatus']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_status: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthStatus']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  auth_step_up_options: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StepUpBody']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
  vocabulary_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Vocabulary']
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorEnvelope']
        }
      }
    }
  }
}
