"""The push guard against commands that try to hide a publish, and ordinary work it must allow."""

import pytest

from labhq.guards import check_command

EVASIONS = [
    "git push",
    "git push origin HEAD:main --force",
    "git -c x=y push",
    "git -c user.name=a -c user.email=b push origin",
    "git --git-dir=.git push origin",
    "git --git-dir .git --work-tree . push",
    "git -C /tmp/elsewhere --no-pager push",
    "env A=1 git push",
    "env -i PATH=/usr/bin git push",
    "env -S 'git push'",
    "A=1 B=2 git push",
    "command git push",
    "builtin command git push",
    "exec git push",
    "/usr/bin/git push",
    "./git push",
    "/usr/lib/git-core/git-push origin",
    "git-send-pack origin main",
    "sh -c 'git push'",
    'bash -lc "git push origin main"',
    "bash -o pipefail -c 'git push'",
    "zsh -c 'cd repo && git push'",
    "sh -c \"bash -c 'git push'\"",
    "true; git push",
    "true && git push",
    "false || git push",
    "echo hi | git push",
    "git status\ngit push",
    "git status & git push",
    "echo $(git push)",
    'echo "$(git push)"',
    "echo `git push`",
    "a=$(git push)",
    "cat <(git push)",
    "echo $(echo $(git push))",
    "{ git push; }",
    "(git push)",
    "if true; then git push; fi",
    "for b in a; do git push; done",
    "! git push",
    "> out git push",
    "2>/dev/null git push",
    "git push > /dev/null 2>&1",
    "bash <<< 'git push'",
    "bash <<EOF\ngit push\nEOF",
    "bash <<'EOF'\necho 'it is fine\ngit push\nEOF",
    "eval git push",
    "eval 'git pu''sh'",
    "trap 'git push' EXIT",
    "alias p='git push'",
    "timeout 30 git push",
    "timeout -s KILL 30 git push",
    "nice -n 5 git push",
    "nohup git push &",
    "time git push",
    "stdbuf -oL git push",
    "sudo -u deploy git push",
    "su -c 'git push' deploy",
    "flock /tmp/lock git push",
    "watch -n 1 git push",
    "ssh build-host git push",
    "xargs git < subcommands.txt",
    "echo push | xargs git",
    "find . -maxdepth 0 -exec git push \\;",
    "git p''ush",
    'git "push"',
    "git \\push",
    "git {push,}",
    "git pu?h",
    "G=git; $G push",
    "${GIT:-git} push",
    "git $(echo push)",
    "git -c alias.p=push p",
    "git -c alias.p='!git push' p",
    "git --config-env=alias.p=PUSH_ALIAS p",
    "git -c url./tmp/r.pushInsteadOf=/dev/null p",
    "git config alias.p push",
    "git config --global alias.publish '!git push'",
    "git config remote.origin.pushurl https://example.invalid/r.git",
    "git config --worktree --unset remote.origin.pushurl",
    "git config url.https://example.invalid/.insteadOf /dev/null/",
    "git config --remove-section remote.origin",
    "git config --edit",
    "git remote set-url --push origin https://example.invalid/r.git",
    "git rebase -x 'git push' main",
    "git submodule foreach 'git push'",
    "git bisect run git push",
    "gh pr merge 12",
    "gh pr merge --squash --admin 12",
    "gh pr create --fill",
    "gh pr review --approve 12",
    "gh repo delete owner/repo --yes",
    "gh release create v1",
    "gh alias set p 'pr merge'",
    "gh api -X POST repos/o/r/pulls",
    "gh api --method=PUT repos/o/r/pulls/1/merge",
    "gh api -XDELETE repos/o/r/git/refs/heads/main",
    "gh api repos/o/r/merges -f base=main -f head=x",
    "gh api graphql -F query=@mutation.graphql",
    "echo 'unterminated",
]

ORDINARY = [
    "git status",
    "git status --short",
    "git add -A",
    "git commit -m 'feat: add parser'",
    'git commit -m "git push later, after review"',
    "git diff HEAD~1 2>&1 | cat",
    "git log --oneline | head -20",
    "git -C sub status",
    "git -c color.ui=never log -1",
    "git stash push -m wip",
    "git stash pop",
    "git branch -a",
    "git switch -c scratch",
    "git rebase main",
    "git help push",
    "git config user.name",
    "git remote -v",
    "git fetch origin",
    "pytest",
    "uv run pytest -q tests/guards",
    "uv run ruff check . && uv run mypy",
    "ls -la && cat README.md",
    "grep -rn 'git push' docs/",
    "echo 'git push'",
    "rg 'gh pr merge' src",
    "for f in *.py; do ruff format $f; done",
    "cat > notes.md <<'EOF'\nDon't push yet.\nEOF",
    "python -m labhq --version",
    "gh pr view 12",
    "gh pr list -R owner/repo",
    "gh pr checks 12",
    "gh issue view 7",
    "gh api repos/o/r/pulls",
    "gh api -X GET search/issues -f q=repo:o/r",
    "gh search issues guard",
    "timeout 60 pytest -x",
    "env PYTHONPATH=src python -c 'print(1)'",
    "find . -name '*.pyc' -exec rm {} +",
    "sh -c 'pytest -q'",
    "",
]


def test_the_corpus_is_large_enough() -> None:
    assert len(EVASIONS) >= 20


@pytest.mark.parametrize("command", EVASIONS)
def test_the_guard_denies_publishing(command: str) -> None:
    verdict = check_command(command)

    assert not verdict.allowed
    assert verdict.reasons


@pytest.mark.parametrize("command", ORDINARY)
def test_the_guard_allows_ordinary_work(command: str) -> None:
    verdict = check_command(command)

    assert verdict.allowed, verdict.reasons
