"""CHANGELOG.md is generated by git-cliff and a hand edit fails the check (CONTRIBUTING §5)."""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from tools import changelog

REPO_ROOT = Path(__file__).resolve().parents[2]

GIT_ENV = {
    "GIT_AUTHOR_NAME": "Test",
    "GIT_AUTHOR_EMAIL": "test@example.invalid",
    "GIT_COMMITTER_NAME": "Test",
    "GIT_COMMITTER_EMAIL": "test@example.invalid",
    "GIT_AUTHOR_DATE": "2026-01-02T03:04:05+00:00",
    "GIT_COMMITTER_DATE": "2026-01-02T03:04:05+00:00",
    "GIT_CONFIG_GLOBAL": os.devnull,
    "GIT_CONFIG_NOSYSTEM": "1",
}


def git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", *args], cwd=repo, env={**os.environ, **GIT_ENV}, check=True, capture_output=True
    )


def commit(repo: Path, message: str) -> None:
    git(repo, "commit", "--allow-empty", "-m", message)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    git(tmp_path, "init", "--initial-branch=main")
    shutil.copy(REPO_ROOT / changelog.CONFIG, tmp_path / changelog.CONFIG)
    git(tmp_path, "add", changelog.CONFIG)
    commit(tmp_path, "build: add the changelog configuration")
    commit(tmp_path, "feat(cli): add the first command")
    commit(tmp_path, "fix: handle an empty project list")
    git(tmp_path, "tag", "-a", "v0.1.0-alpha.1", "-m", "v0.1.0-alpha.1")
    return tmp_path


def generate(repo: Path, *args: str) -> str:
    assert changelog.main(["--repo", str(repo), *args]) == 0
    return (repo / changelog.CHANGELOG).read_text(encoding="utf-8")


def test_generates_one_section_per_tag_grouped_by_type(repo: Path) -> None:
    commit(repo, "docs: describe the release")
    git(repo, "tag", "-a", "v0.2.0-beta.1", "-m", "v0.2.0-beta.1")

    text = generate(repo)

    assert text.index("## v0.2.0-beta.1") < text.index("## v0.1.0-alpha.1")
    assert "### Features\n\n- **cli:** add the first command" in text
    assert "### Fixes\n\n- handle an empty project list" in text
    assert "### Documentation\n\n- describe the release" in text


def test_fresh_file_passes_the_check(repo: Path) -> None:
    generate(repo)

    assert changelog.main(["--repo", str(repo), "--check"]) == 0


def test_hand_edit_fails_the_check(repo: Path, capsys: pytest.CaptureFixture[str]) -> None:
    path = repo / changelog.CHANGELOG
    generate(repo)
    path.write_text(path.read_text(encoding="utf-8") + "- a line nobody committed\n")

    assert changelog.main(["--repo", str(repo), "--check"]) == 1
    out = capsys.readouterr().out
    assert "-- a line nobody committed" in out
    assert "never edited by hand" in out


def test_missing_file_fails_the_check(repo: Path) -> None:
    assert changelog.main(["--repo", str(repo), "--check"]) == 1


def test_unreleased_commits_leave_the_file_unchanged(repo: Path) -> None:
    before = generate(repo)
    commit(repo, "feat: something not yet released")

    assert generate(repo) == before
    assert changelog.main(["--repo", str(repo), "--check"]) == 0


def test_upcoming_tag_survives_its_own_release_commit(repo: Path) -> None:
    commit(repo, "feat: ship the beta")
    prepared = generate(repo, "--tag", "v0.2.0-beta.1")
    assert "## v0.2.0-beta.1" in prepared
    assert "- ship the beta" in prepared

    # The owner commits the regenerated file as chore(release) and tags that commit; the
    # release commit is skipped, so CI regenerates the same file after the tag lands.
    git(repo, "add", changelog.CHANGELOG)
    commit(repo, "chore(release): v0.2.0-beta.1")
    git(repo, "tag", "-a", "v0.2.0-beta.1", "-m", "v0.2.0-beta.1")

    assert changelog.main(["--repo", str(repo), "--check"]) == 0
