"""add login requests and channels

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-09 22:04:30.040400

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0020"
down_revision: str | Sequence[str] | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("pane", sa.String(length=64), nullable=True),
        sa.Column("awaits_code", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "stage IN ('pending', 'completed', 'expired', 'failed')", name="login_stage"
        ),
        sa.CheckConstraint(
            "stage IN ('pending', 'completed', 'expired', 'failed')",
            name=op.f("ck_login_requests_login_stage"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_requests")),
    )
    with op.batch_alter_table("login_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_login_requests_tool_account_stage", ["tool", "account", "stage"], unique=False
        )
        batch_op.create_index(
            "uq_login_requests_pending",
            ["tool", "account"],
            unique=True,
            sqlite_where=sa.text("stage = 'pending'"),
            postgresql_where=sa.text("stage = 'pending'"),
        )

    op.create_table(
        "notification_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_test_ok", sa.Boolean(), nullable=True),
        sa.Column("last_test_error", sa.Text(), nullable=True),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channels")),
        sa.UniqueConstraint("name", name=op.f("uq_notification_channels_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_channels")
    with op.batch_alter_table("login_requests", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_login_requests_pending",
            sqlite_where=sa.text("stage = 'pending'"),
            postgresql_where=sa.text("stage = 'pending'"),
        )
        batch_op.drop_index("ix_login_requests_tool_account_stage")

    op.drop_table("login_requests")
    # ### end Alembic commands ###
