"""add decision room columns

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-10 00:22:09.092911

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0022"
down_revision: str | Sequence[str] | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting_action_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("approval_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_meeting_action_items_approval_id_approvals"),
            "approvals",
            ["approval_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pinned_kind", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("pinned_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("estimate_micros", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("waiting_agent_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("waiting_reason", sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_meetings_waiting_agent_id_agents"),
            "agents",
            ["waiting_agent_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_meetings_waiting_agent_id_agents"), type_="foreignkey"
        )
        batch_op.drop_column("waiting_reason")
        batch_op.drop_column("waiting_agent_id")
        batch_op.drop_column("estimate_micros")
        batch_op.drop_column("pinned_id")
        batch_op.drop_column("pinned_kind")

    with op.batch_alter_table("meeting_action_items", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_meeting_action_items_approval_id_approvals"), type_="foreignkey"
        )
        batch_op.drop_column("approval_id")

    # ### end Alembic commands ###
