"""add room forecast columns

Revision ID: 0023
Revises: 0022
Create Date: 2026-10-10 02:44:36.442222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0023"
down_revision: str | Sequence[str] | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("estimate_high_micros", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("estimate_source", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("cost_cap_micros", sa.BigInteger(), nullable=True))
        batch_op.add_column(
            sa.Column("over_estimate_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_column("over_estimate_at")
        batch_op.drop_column("cost_cap_micros")
        batch_op.drop_column("estimate_source")
        batch_op.drop_column("estimate_high_micros")

    # ### end Alembic commands ###
