"""Declarative base, constraint naming and column types shared by every table."""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import JSON, BigInteger, DateTime, Dialect, Enum, MetaData
from sqlalchemy.orm import DeclarativeBase, mapped_column
from sqlalchemy.types import TypeDecorator

from labhq.clock import ensure_utc

# Deterministic names keep autogenerated migrations stable and SQLite batch moves possible.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class UTCDateTime(TypeDecorator[datetime]):
    """Accepts only aware datetimes and always returns aware UTC.

    SQLite stores no offset, so the value is normalised to UTC on the way in and tagged as
    UTC on the way out.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        return ensure_utc(value).replace(tzinfo=None)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        return ensure_utc(value) if value.tzinfo else value.replace(tzinfo=UTC)


def enum_column(enum_type: type[StrEnum], name: str) -> Enum:
    """A string column restricted to a vocabulary, checked by the database too."""
    return Enum(
        enum_type,
        name=name,
        native_enum=False,
        create_constraint=True,
        length=32,
        validate_strings=True,
        values_callable=lambda members: [member.value for member in members],
    )


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {  # noqa: RUF012
        datetime: UTCDateTime(),
        dict[str, Any]: JSON(),
        list[Any]: JSON(),
    }


def micros_column(*, nullable: bool) -> Any:
    """An amount in integer micro-USD (ADR 0002)."""
    return mapped_column(BigInteger, nullable=nullable)
