"""List the native Windows limitations from the `posix_only` markers in the platforms guide.

The markers (tests/platforms.py) are the source of truth; `docs/guide/platforms.md` carries
a generated table between two comment lines. The default run fails when the table does not
match the markers, `--write` regenerates it. Markers are read statically, so a reason must
be a string literal.
"""

import argparse
import ast
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

MARKER = "posix_only"
GUIDE = Path("docs/guide/platforms.md")
TESTS = Path("tests")
START = "<!-- platform-limits:start (generated by tools/platform_limits.py) -->"
END = "<!-- platform-limits:end -->"


@dataclass(frozen=True, order=True)
class Limitation:
    test: str
    reason: str


class MarkerError(ValueError):
    pass


def _is_marker(node: ast.AST) -> bool:
    # pytest.mark.posix_only, or mark.posix_only after `from pytest import mark`.
    return (
        isinstance(node, ast.Attribute)
        and node.attr == MARKER
        and isinstance(node.value, ast.Attribute | ast.Name)
        and (node.value.attr if isinstance(node.value, ast.Attribute) else node.value.id) == "mark"
    )


class _Finder(ast.NodeVisitor):
    def __init__(self, location: str) -> None:
        self.location = location
        self.scope: list[str] = []
        self.in_pytestmark = False
        self.found: list[Limitation] = []

    def _visit_scope(self, node: ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef) -> None:
        # Decorators are children of the definition, so a mark on it lands in its scope.
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._visit_scope(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._visit_scope(node)

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        self._visit_scope(node)

    def visit_Assign(self, node: ast.Assign) -> None:
        names = [target.id for target in node.targets if isinstance(target, ast.Name)]
        self.in_pytestmark = not self.scope and names == ["pytestmark"]
        self.generic_visit(node)
        self.in_pytestmark = False

    def visit_Call(self, node: ast.Call) -> None:
        if not _is_marker(node.func):
            self.generic_visit(node)
            return
        if not self.scope and not self.in_pytestmark:
            # An alias would be listed against the module, not the tests that use it.
            raise MarkerError(f"{self._test()}: use {MARKER} on a test or in `pytestmark`")
        self.found.append(Limitation(self._test(), self._reason(node)))

    def visit_Attribute(self, node: ast.Attribute) -> None:
        # Only reached for a mark that is not called, which carries no reason.
        if _is_marker(node):
            raise MarkerError(f"{self._test()}: {MARKER} needs a reason")
        self.generic_visit(node)

    def _test(self) -> str:
        return "::".join([self.location, *self.scope])

    def _reason(self, node: ast.Call) -> str:
        args = node.args
        if len(args) != 1 or node.keywords:
            raise MarkerError(f"{self._test()}: {MARKER} takes exactly one reason")
        reason = args[0]
        if not isinstance(reason, ast.Constant) or not isinstance(reason.value, str):
            raise MarkerError(f"{self._test()}: the {MARKER} reason must be a string literal")
        if not reason.value.strip():
            raise MarkerError(f"{self._test()}: the {MARKER} reason is empty")
        return " ".join(reason.value.split())


def limitations(root: Path) -> list[Limitation]:
    found: set[Limitation] = set()
    for path in sorted((root / TESTS).rglob("*.py")):
        finder = _Finder(path.relative_to(root).as_posix())
        finder.visit(ast.parse(path.read_text(encoding="utf-8"), filename=str(path)))
        found.update(finder.found)
    return sorted(found)


def render(found: list[Limitation]) -> str:
    rows = [f"| `{item.test}` | {item.reason} |" for item in found]
    if not rows:
        rows = ["| (none) | |"]
    return "\n".join([START, "", "| Test | Limitation |", "|---|---|", *rows, "", END])


def _replace_block(text: str, block: str) -> Iterator[str]:
    head, start, rest = text.partition(START)
    _, end, tail = rest.partition(END)
    if not start or not end:
        raise MarkerError(f"{GUIDE} has no generated block between {START!r} and {END!r}")
    yield head
    yield block
    yield tail


def updated_guide(root: Path) -> tuple[str, str]:
    """The guide as it is and as the markers say it should be."""
    current = (root / GUIDE).read_text(encoding="utf-8")
    return current, "".join(_replace_block(current, render(limitations(root))))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--write", action="store_true", help="regenerate the guide's table")
    args = parser.parse_args(argv)

    try:
        current, expected = updated_guide(args.root)
    except MarkerError as error:
        print(f"error: {error}")
        return 1
    if args.write:
        (args.root / GUIDE).write_text(expected, encoding="utf-8", newline="\n")
        return 0
    if current != expected:
        print(f"error: {GUIDE} does not match the {MARKER} markers;")
        print("run `uv run python -m tools.platform_limits --write` and commit the result")
        return 1
    print(f"platform_limits: {GUIDE} lists {len(limitations(args.root))} limitations")
    return 0


if __name__ == "__main__":
    sys.exit(main())
