"""Generate `docs/guide/configuration.md` from the pydantic settings classes, or check it.

Every `BaseSettings` subclass defined under `labhq` is found by importing the package, so a
new class or field needs no registration here. A field's text is its `Field(description=...)`
or, failing that, the comment block directly above it in the class body. `--check` fails
when the checked-in page differs from what the classes produce now.
"""

import argparse
import ast
import importlib
import inspect
import json
import pkgutil
import sys
import textwrap
from collections.abc import Iterator
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from types import ModuleType
from typing import Any

from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined
from pydantic_settings import BaseSettings

PAGE = Path("docs/guide/configuration.md")
PACKAGE = "labhq"
# Factories whose result is the same on every machine, so it can be printed as the default.
CONSTANT_FACTORIES: tuple[type, ...] = (dict, list, set, frozenset, tuple)

HEADER = """\
# Configuration

<!-- Generated by `uv run python -m tools.settings_doc`. Do not edit by hand: CI fails when
this page differs from the settings classes. -->

labhq reads its settings from environment variables. Every variable is optional: an unset
variable keeps the default shown here. Values for lists, sets and mappings are JSON, for
example `LABHQ_MEETINGS_CADENCE_SECONDS='{"standup": 86400}'`.

The one variable labhq passes to the agents it starts is `ANTHROPIC_API_KEY`, and only when
you set it: it switches Claude Code to API billing (see [Security](security.md#billing)).
labhq has no setting for any other credential of Claude's and never reads one.

A default marked *computed* is worked out on your machine when labhq starts: `LABHQ_DATA_DIR`
is the platform's user data directory for `labhq` (for example `~/.local/share/labhq` on
Linux), and `LABHQ_HEALTH_LOCAL_HOST_NAME` is the machine's host name.
"""


@dataclass(frozen=True)
class Row:
    variable: str
    type: str
    default: str
    description: str


@dataclass(frozen=True)
class Section:
    title: str
    summary: str
    rows: tuple[Row, ...]


def _modules(package: ModuleType) -> Iterator[str]:
    for info in pkgutil.walk_packages(package.__path__, f"{package.__name__}."):
        # `__main__` modules run the CLI when imported.
        if info.name.rsplit(".", 1)[-1] != "__main__":
            yield info.name


def settings_classes(package_name: str = PACKAGE) -> list[type[BaseSettings]]:
    package = importlib.import_module(package_name)
    for name in _modules(package):
        importlib.import_module(name)
    found: dict[str, type[BaseSettings]] = {}
    pending: list[type[BaseSettings]] = [BaseSettings]
    while pending:
        for cls in pending.pop().__subclasses__():
            pending.append(cls)
            if cls.__module__ == package_name or cls.__module__.startswith(f"{package_name}."):
                found[f"{cls.__module__}.{cls.__qualname__}"] = cls
    return [found[key] for key in sorted(found)]


def _comments_above_fields(cls: type) -> dict[str, str]:
    """The `#` block directly above each annotated field of the class body."""
    try:
        source = textwrap.dedent(inspect.getsource(cls))
    except (OSError, TypeError):
        return {}
    lines = source.splitlines()
    tree = ast.parse(source)
    body = tree.body[0].body if tree.body and isinstance(tree.body[0], ast.ClassDef) else []
    comments: dict[str, str] = {}
    for node in body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        block: list[str] = []
        index = node.lineno - 2
        while index >= 0 and lines[index].strip().startswith("#"):
            block.insert(0, lines[index].strip().lstrip("#").strip())
            index -= 1
        if block:
            comments[node.target.id] = " ".join(block)
    return comments


def _type_name(annotation: Any) -> str:
    if isinstance(annotation, type) and not getattr(annotation, "__args__", None):
        return annotation.__name__
    text = str(annotation)
    for prefix in ("typing.", "pathlib.", "pydantic.types.", "datetime."):
        text = text.replace(prefix, "")
    return text


def _render_value(value: Any) -> str:
    if value is None:
        return "unset"
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (set, frozenset)):
        value = sorted(value)
    if isinstance(value, (list, tuple, dict)):
        return f"`{json.dumps(value, sort_keys=True)}`"
    return f"`{value}`"


def _default(field: FieldInfo) -> str:
    factory = field.default_factory
    if factory is not None:
        if factory in CONSTANT_FACTORIES:
            return _render_value(factory())  # type: ignore[call-arg]
        return "*computed*"
    if field.default is PydanticUndefined:
        return "*required*"
    return _render_value(field.default)


def _variable(cls: type[BaseSettings], name: str, field: FieldInfo) -> str:
    alias = field.validation_alias or field.alias
    if isinstance(alias, str):
        return alias.upper()
    prefix = str(cls.model_config.get("env_prefix", ""))
    return f"{prefix}{name}".upper()


def _summary(cls: type) -> str:
    doc = cls.__doc__ if cls.__doc__ and cls.__doc__ is not BaseSettings.__doc__ else None
    doc = doc or sys.modules[cls.__module__].__doc__ or ""
    return " ".join(doc.strip().split("\n\n", 1)[0].split())


def section(cls: type[BaseSettings]) -> Section:
    comments = _comments_above_fields(cls)
    rows = tuple(
        Row(
            variable=_variable(cls, name, field),
            type=_type_name(field.annotation),
            default=_default(field),
            description=" ".join((field.description or comments.get(name, "")).split()),
        )
        for name, field in cls.model_fields.items()
    )
    return Section(f"`{cls.__module__}.{cls.__qualname__}`", _summary(cls), rows)


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(classes: list[type[BaseSettings]]) -> str:
    parts = [HEADER]
    for item in (section(cls) for cls in classes):
        if not item.rows:
            continue
        parts.append(f"## {item.title}\n")
        if item.summary:
            parts.append(f"{item.summary}\n")
        table = ["| Variable | Type | Default | Description |", "|---|---|---|---|"]
        table.extend(
            f"| `{row.variable}` | `{_cell(row.type)}` | {_cell(row.default)} "
            f"| {_cell(row.description)} |"
            for row in item.rows
        )
        parts.append("\n".join(table) + "\n")
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true", help="Fail if the page is stale.")
    args = parser.parse_args(argv)

    classes = settings_classes()
    if not classes:
        # A guard that found nothing must not pass (CONTRIBUTING.md §6).
        print(f"error: no settings classes found under {PACKAGE}")
        return 1
    expected = render(classes)
    page = args.root / PAGE
    if not args.check:
        page.write_text(expected, encoding="utf-8")
        print(f"settings_doc: wrote {PAGE} from {len(classes)} settings classes")
        return 0
    current = page.read_text(encoding="utf-8") if page.is_file() else ""
    if current != expected:
        print(
            f"error: {PAGE} does not match the settings classes. "
            "Run `uv run python -m tools.settings_doc` and commit the result."
        )
        return 1
    print(f"settings_doc: {PAGE} matches {len(classes)} settings classes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
